/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppLayoutImport } from './routes/_appLayout'
import { Route as IndexImport } from './routes/index'
import { Route as AppLayoutPocImport } from './routes/_appLayout/poc'
import { Route as AppLayoutDailyUi3Import } from './routes/_appLayout/daily-ui-3'
import { Route as AppLayoutDailyUi21Import } from './routes/_appLayout/daily-ui-21'

// Create/Update Routes

const AppLayoutRoute = AppLayoutImport.update({
  id: '/_appLayout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppLayoutPocRoute = AppLayoutPocImport.update({
  id: '/poc',
  path: '/poc',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutDailyUi3Route = AppLayoutDailyUi3Import.update({
  id: '/daily-ui-3',
  path: '/daily-ui-3',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutDailyUi21Route = AppLayoutDailyUi21Import.update({
  id: '/daily-ui-21',
  path: '/daily-ui-21',
  getParentRoute: () => AppLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_appLayout': {
      id: '/_appLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_appLayout/daily-ui-21': {
      id: '/_appLayout/daily-ui-21'
      path: '/daily-ui-21'
      fullPath: '/daily-ui-21'
      preLoaderRoute: typeof AppLayoutDailyUi21Import
      parentRoute: typeof AppLayoutImport
    }
    '/_appLayout/daily-ui-3': {
      id: '/_appLayout/daily-ui-3'
      path: '/daily-ui-3'
      fullPath: '/daily-ui-3'
      preLoaderRoute: typeof AppLayoutDailyUi3Import
      parentRoute: typeof AppLayoutImport
    }
    '/_appLayout/poc': {
      id: '/_appLayout/poc'
      path: '/poc'
      fullPath: '/poc'
      preLoaderRoute: typeof AppLayoutPocImport
      parentRoute: typeof AppLayoutImport
    }
  }
}

// Create and export the route tree

interface AppLayoutRouteChildren {
  AppLayoutDailyUi21Route: typeof AppLayoutDailyUi21Route
  AppLayoutDailyUi3Route: typeof AppLayoutDailyUi3Route
  AppLayoutPocRoute: typeof AppLayoutPocRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutDailyUi21Route: AppLayoutDailyUi21Route,
  AppLayoutDailyUi3Route: AppLayoutDailyUi3Route,
  AppLayoutPocRoute: AppLayoutPocRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppLayoutRouteWithChildren
  '/daily-ui-21': typeof AppLayoutDailyUi21Route
  '/daily-ui-3': typeof AppLayoutDailyUi3Route
  '/poc': typeof AppLayoutPocRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppLayoutRouteWithChildren
  '/daily-ui-21': typeof AppLayoutDailyUi21Route
  '/daily-ui-3': typeof AppLayoutDailyUi3Route
  '/poc': typeof AppLayoutPocRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_appLayout': typeof AppLayoutRouteWithChildren
  '/_appLayout/daily-ui-21': typeof AppLayoutDailyUi21Route
  '/_appLayout/daily-ui-3': typeof AppLayoutDailyUi3Route
  '/_appLayout/poc': typeof AppLayoutPocRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/daily-ui-21' | '/daily-ui-3' | '/poc'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/daily-ui-21' | '/daily-ui-3' | '/poc'
  id:
    | '__root__'
    | '/'
    | '/_appLayout'
    | '/_appLayout/daily-ui-21'
    | '/_appLayout/daily-ui-3'
    | '/_appLayout/poc'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppLayoutRoute: AppLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_appLayout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_appLayout": {
      "filePath": "_appLayout.tsx",
      "children": [
        "/_appLayout/daily-ui-21",
        "/_appLayout/daily-ui-3",
        "/_appLayout/poc"
      ]
    },
    "/_appLayout/daily-ui-21": {
      "filePath": "_appLayout/daily-ui-21.tsx",
      "parent": "/_appLayout"
    },
    "/_appLayout/daily-ui-3": {
      "filePath": "_appLayout/daily-ui-3.tsx",
      "parent": "/_appLayout"
    },
    "/_appLayout/poc": {
      "filePath": "_appLayout/poc.tsx",
      "parent": "/_appLayout"
    }
  }
}
ROUTE_MANIFEST_END */
