/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppLayoutImport } from './routes/_appLayout'
import { Route as IndexImport } from './routes/index'
import { Route as AppLayoutPocImport } from './routes/_appLayout/poc'

// Create/Update Routes

const AppLayoutRoute = AppLayoutImport.update({
  id: '/_appLayout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppLayoutPocRoute = AppLayoutPocImport.update({
  id: '/poc',
  path: '/poc',
  getParentRoute: () => AppLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_appLayout': {
      id: '/_appLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_appLayout/poc': {
      id: '/_appLayout/poc'
      path: '/poc'
      fullPath: '/poc'
      preLoaderRoute: typeof AppLayoutPocImport
      parentRoute: typeof AppLayoutImport
    }
  }
}

// Create and export the route tree

interface AppLayoutRouteChildren {
  AppLayoutPocRoute: typeof AppLayoutPocRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutPocRoute: AppLayoutPocRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppLayoutRouteWithChildren
  '/poc': typeof AppLayoutPocRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppLayoutRouteWithChildren
  '/poc': typeof AppLayoutPocRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_appLayout': typeof AppLayoutRouteWithChildren
  '/_appLayout/poc': typeof AppLayoutPocRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/poc'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/poc'
  id: '__root__' | '/' | '/_appLayout' | '/_appLayout/poc'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppLayoutRoute: AppLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_appLayout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_appLayout": {
      "filePath": "_appLayout.tsx",
      "children": [
        "/_appLayout/poc"
      ]
    },
    "/_appLayout/poc": {
      "filePath": "_appLayout/poc.tsx",
      "parent": "/_appLayout"
    }
  }
}
ROUTE_MANIFEST_END */
